version: '2.1'

services:
  proxy:
    build:
      context: ./nginx
    env_file:
      - .env
    volumes:
      - ./nginx/hosts:/etc/hosts
      # - ./logs:/var/log/nginx
    links:
      - backend-a
      - backend-b
      - oauth2-proxy
    depends_on:
      - backend-a
      - backend-b
      - oauth2-proxy
    ports:
      - 8080:80

  oauth2-proxy:
    env_file:
      - .env
    build:
      context: ./oauth2_proxy
    expose:
      - 4180
    links:
      - backend-a
      - backend-b
    volumes:
      - ./oauth2_proxy/run.sh:/run.sh

  backend-a:
    build:
      context: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 5001:5000
    expose:
      - 5000
    environment:
      - SERVER_NAME=Backend A
  backend-b:
    build:
      context: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 5002:5000
    expose:
      - 5000
    environment:
      - SERVER_NAME=Backend B
