version: '2.1'

services:
  proxy:
    build: .
    env_file:
      - .env
  server:
    build:
      context: ./example
    working_dir: /app
    volumes:
      - ./example:/app
    ports:
      - 5000:5000